# Generated by Django 5.2.1 on 2025-06-03 11:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_course_learningpath_skill_pathcourse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UdemyCourse",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.TextField()),
                ("level", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(max_length=500)),
                ("instructors", models.TextField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("price", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
            ],
        ),
    ]
