# Generated by Django 5.2.1 on 2025-06-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_learningpath_new_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
