# Generated by Django 5.2.1 on 2025-06-09 12:02

import django.contrib.postgres.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
