# Generated by Django 5.2.1 on 2025-06-09 14:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningpath",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="learningpath",
            name="current_level",
        ),
        migrations.RemoveField(
            model_name="learningpath",
            name="priority",
        ),
        migrations.AddField(
            model_name="learningpath",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="target_level",
            field=models.CharField(default="Beginner", max_length=50),
        ),
        migrations.CreateModel(
            name="LearningPathCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", models.DateField()),
                ("course_level", models.TextField()),
                ("course_description", models.TextField()),
                ("course_title", models.TextField()),
                ("course_duration", models.TextField()),
                ("course_instructor", models.TextField()),
                ("course_price", models.TextField()),
                ("course_rating", models.FloatField(default=0)),
                ("course_skills", models.TextField()),
                (
                    "course_progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("Current", "Current"),
                            ("Completed", "Completed"),
                            ("Not Started", "Not Started"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learningpath",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learningpath_courses",
                        to="api.learningpath",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PathCourse",
        ),
    ]
