# Generated by Django 5.2.1 on 2025-06-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_learningpath_courses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningpath",
            name="progress",
        ),
    ]
