# Generated by Django 5.2.1 on 2025-06-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_merge_20250610_0459"),
        ("api", "0008_remove_learningpath_progress"),
    ]

    operations = []
