# Generated by Django 5.2.1 on 2025-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_merge_20250610_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpathcourse",
            name="course_url",
            field=models.TextField(default=""),
        ),
    ]
