# Generated by Django 5.2.1 on 2025-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_learningpathcourse_course_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="job_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
