# Generated by Django 5.2.1 on 2025-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_jobpost_job_id_alter_jobpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="job_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
