# Generated by Django 5.2.1 on 2025-06-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_jobpost_job_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructor",
            new_name="instructors",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="course",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="course",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
