# Generated by Django 5.2.1 on 2025-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_rename_instructor_course_instructors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentchunk",
            name="document",
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="course_highlights",
            field=models.TextField(default="[]"),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="course_provider",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="course_students",
            field=models.IntegerField(default=1989),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="name",
            field=models.CharField(default="Custom Learning Path", max_length=255),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_duration",
            field=models.TextField(blank=True, default="0h"),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_instructor",
            field=models.TextField(blank=True, default="N/A"),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_level",
            field=models.TextField(default="Beginner"),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_price",
            field=models.TextField(blank=True, default="0"),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_rating",
            field=models.FloatField(default=3.5),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_skills",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_status",
            field=models.CharField(
                choices=[
                    ("Current", "Current"),
                    ("Completed", "Completed"),
                    ("Not Started", "Not Started"),
                ],
                default="Not Started",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="course_title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="learningpathcourse",
            name="target",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="DocumentChunk",
        ),
    ]
