# Generated by Django 5.2.1 on 2025-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_documentchunk_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="completed_hours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="estimated_hours",
            field=models.FloatField(default=0.0),
        ),
    ]
