# Generated by Django 5.2.1 on 2025-06-13 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_learningpath_completed_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="completed_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="estimated_hours",
            field=models.IntegerField(default=0),
        ),
    ]
