# Generated by Django 5.2.1 on 2025-06-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_learningpath_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
