# Generated by Django 5.2.1 on 2025-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_learningpath_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="completed_hours",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="learningpath",
            name="estimated_hours",
            field=models.FloatField(default=0.0),
        ),
    ]
